// <auto-generated />
using HikingTrail.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HikingTrail.Migrations
{
    [DbContext(typeof(HikingTrailContext))]
    [Migration("20220118232609_AddSeasons")]
    partial class AddSeasons
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("HikingTrail.Models.Trail", b =>
                {
                    b.Property<int>("TrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Configuration")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Difficulty")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("DistanceFromPdx")
                        .HasColumnType("double");

                    b.Property<int>("ElevationGain")
                        .HasColumnType("int");

                    b.Property<string>("FamilyFriendly")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Length")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Season")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("TrailId");

                    b.ToTable("Trails");
                });
#pragma warning restore 612, 618
        }
    }
}
